import { ChakraProvider } from '@chakra-ui/react';
import type { AppProps } from 'next/app';
import { theme } from '../theme';
import Head from 'next/head';
import { ReactElement, ReactNode, useState } from 'react';
import { NextPage } from 'next';
import { Hydrate, QueryClient, QueryClientProvider } from 'react-query';

export type NextPageWithLayout<P = Record<string, any>, IP = P> = NextPage<P, IP> & {
    getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
    Component: NextPageWithLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
    const [queryClient] = useState(() => new QueryClient());

    const getLayout = Component.getLayout || ((page) => page);

    return (
        <>
            <Head>
                <link rel='icon' href='/bbicon.svg' />
                <title>Bitsbook | Join the college conversation</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
            </Head>
            <ChakraProvider theme={theme}>
                <QueryClientProvider client={queryClient}>
                    <Hydrate state={pageProps.dehydratedState}>
                        {getLayout(<Component {...pageProps} />)}
                    </Hydrate>
                </QueryClientProvider>
            </ChakraProvider>
        </>
    );
}
